### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by kcallenxu** [fillup/walmart-partner-api-sdk-php#12]
use composer to install:
composer.json:
{
  "minimum-stability": "dev",
  "require": {
    "fillup/walmart-partner-api-sdk-php": "^1.0.5"
  }
}

**Comment by fillup** [comment]
Sorry, I'll update the readme. You need to explicitly require `"guzzlehttp/guzzle-services": "dev-master"`. I'm hoping that project can create a new version tag so that it will be considered stable, but in the mean time you need to include `dev-master` for it yourself so guzzle doesn't complain. So update your require to be (at least):

``` json
{
  "require": {
    "fillup/walmart-partner-api-sdk-php": "^1.0.5",
    "guzzlehttp/guzzle-services": "dev-master"
  }
}
```

Let me know if that resolves it for you or if you have a different issue.
